name: Generate a build from main and push to gh-pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: build and push to gh-pages
    steps:
      - name: git-checkout
        uses: actions/checkout@v3.3.0
      
      - name: install node modules
        run: npm i
        
      - name: build vite + react app
        run: npm run build
      
      - name: push build to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
  